modLoader="javafml"
loaderVersion="[34,)"
license="GPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Portals/issues"
#displayURL="cuseforge URL"
#logoFile="logo.png"

[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modName}"
	credits="${modCredits}"
	authors="${modAuthor}"
	description="${modDescription}"

[[dependencies.betterportals]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterportals]]
    modId="yungsapi"
    versionRange="[1.16.3-Forge-1,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"