modLoader="javafml"
loaderVersion="[35,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Portals/issues"

[[mods]]
    modId="${modId}"
    version="${version}"
    displayName="${modName}"
    credits="${modCredits}"
    authors="${modAuthor}"
    description="${modDescription}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-portals"
    logoFile="logo.png"

[[dependencies.betterportals]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterportals]]
    modId="yungsapi"
    versionRange="[1.16.4-Forge-6,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"