modLoader="javafml"
loaderVersion="[35,)"
license="GPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Portals/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-portals"
logoFile="logo.png"

[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modName}"
	credits="${modCredits}"
	authors="${modAuthor}"
	description="${modDescription}"

[[dependencies.betterportals]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterportals]]
    modId="yungsapi"
    versionRange="[1.16.4-Forge-3,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"