package com.yungnickyoung.minecraft.betterportals.world.feature;

import com.yungnickyoung.minecraft.betterportals.BetterPortals;
import com.yungnickyoung.minecraft.betterportals.init.BPModBlocks;
import com.yungnickyoung.minecraft.betterportals.world.variant.PortalLakeVariantSettings;
import com.yungnickyoung.minecraft.betterportals.world.variant.PortalLakeVariants;
import com.yungnickyoung.minecraft.yungsapi.world.BlockSetSelector;
import mcp.MethodsReturnNonnullByDefault;
import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.block.material.Material;
import net.minecraft.util.Direction;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.ISeedReader;
import net.minecraft.world.gen.ChunkGenerator;
import net.minecraft.world.gen.feature.Feature;
import net.minecraft.world.gen.feature.NoFeatureConfig;

import javax.annotation.ParametersAreNonnullByDefault;
import java.util.Objects;
import java.util.Random;

@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
public class PortalLakeFeature extends Feature<NoFeatureConfig> {
    private static final BlockState PORTAL_FLUID = BPModBlocks.PORTAL_FLUID_BLOCK.getDefaultState();

    public PortalLakeFeature() {
        super(NoFeatureConfig.field_236558_a_);
    }

    @Override
    public boolean generate(ISeedReader world, ChunkGenerator chunkGenerator, Random random, BlockPos pos, NoFeatureConfig config) {
        // Attempt to get dimension name, e.g. "minecraft:the_nether"
        String dimensionName;
        try {
            dimensionName = Objects.requireNonNull(world.getWorld().getDimensionKey().getLocation()).toString();
        } catch (NullPointerException e) {
            BetterPortals.LOGGER.error("ERROR: Unable to get dimension name!");
            return false;
        }

        // Grab proper settings, depending on dimension
        PortalLakeVariantSettings settings = PortalLakeVariants.get().getVariantForDimension(dimensionName);

        // Settings are null -> no variant for this dimension
        if (settings == null) {
            return false;
        }

        // Determine if we should spawn
        if (random.nextFloat() > settings.getSpawnChance() / 2 / 2) { // Divide by two because we have two portal lake variants.
            return false;                                             // Divide by two again since this variant has no restrictions on placement.
        }

        BlockSetSelector selector = settings.getBlockSelector();

        int y = (settings.getMaxY() - settings.getMinY()) + settings.getMinY() - 3; // offset by -3 since this variant has the liquid a little higher up
        pos = new BlockPos(pos.getX(), y, pos.getZ());
        BlockPos.Mutable mutable = new BlockPos.Mutable();

        // Generate structure.
        // This is all super long and ugly because it comes from a Python script I wrote to convert
        // structure NBT files to code.
        mutable.setPos(pos.getX() + 4, pos.getY(), pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY(), pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY(), pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY(), pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY(), pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY(), pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY(), pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY(), pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY(), pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY(), pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY(), pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY(), pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 1, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 1, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 1, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 1, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 1, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 1, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 1, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 1, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 1, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 1, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 1, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 1, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 1, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 1, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 2, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 2, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 2, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 2, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 2, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 2, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 2, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 2, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 2, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 2, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 2, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 2, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 2, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 2, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 2, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 2, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 2, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 2, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 2, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 2, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 2, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 3, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 3, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 3, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 3, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 3, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 3, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 4, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 4, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 4, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 4, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 4, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 4, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 5, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 5, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 5, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 5, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ());
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 11);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX(), pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 11, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 1);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 2);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 10);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 9, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 9, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 9, pos.getZ() + 9);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 9, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 9, pos.getZ() + 6);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 10, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 10, pos.getZ() + 8);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 10, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 10, pos.getZ() + 5);
        world.setBlockState(mutable, selector.get(random), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 1, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 1, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 1, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 1, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 1, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 1, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 1, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 1, pos.getZ() + 7);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 1, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 1, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 2, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 2, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 2, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 2, pos.getZ() + 3);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 2, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 2, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 2, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 2, pos.getZ() + 7);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 2, pos.getZ() + 3);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 2, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 2, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 2, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 2, pos.getZ() + 7);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 2, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 2, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 2, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 2, pos.getZ() + 7);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 2, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 2, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 3);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 4);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 3, pos.getZ() + 7);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 5);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 3, pos.getZ() + 6);
        world.setBlockState(mutable, PORTAL_FLUID, 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 4, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 4, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 5, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 5, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 5, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 5, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 5, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 5, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 5, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 5, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 5, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 6, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 6, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 6, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 6, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 6, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 6, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 6, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 6, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 6, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 6, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 6, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 6, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 6, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 6, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 6, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 6, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 6, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 6, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 7, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 7, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 7, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 7, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 7, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 7, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 7, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 7, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 7, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 7, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 7, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 7, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 7, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 7, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 7, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 7, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 7, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 7, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 7, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 7, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 7, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 7, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 7, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 7, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 8, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 8, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 8, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 8, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 8, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 8, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 8, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 8, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 8, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 8, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 8, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 8, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 8, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 8, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 8, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 8, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 8, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 8, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 8, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 8, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 8, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 8, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 8, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 8, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 8, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 8, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 8, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 10, pos.getY() + 8, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 1, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 9, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 2, pos.getY() + 9, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 9, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 9, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 9, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 9, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 9, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 9, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 9, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 9, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 9, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 9, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 9, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 9, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 9, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 9, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 9, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 9, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 9, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 9, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 9, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 9, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 9, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 9, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 9, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 9, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 9, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 9, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 8, pos.getY() + 9, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 9, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 9, pos.getY() + 9, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 10, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 10, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 3, pos.getY() + 10, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 10, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 10, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 10, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 10, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 10, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 10, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 4, pos.getY() + 10, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 10, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 10, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 10, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 10, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 10, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 10, pos.getZ() + 8);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 5, pos.getY() + 10, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 10, pos.getZ() + 2);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 10, pos.getZ() + 3);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 10, pos.getZ() + 4);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 10, pos.getZ() + 5);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 10, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 10, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 6, pos.getY() + 10, pos.getZ() + 9);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 10, pos.getZ() + 6);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);
        mutable.setPos(pos.getX() + 7, pos.getY() + 10, pos.getZ() + 7);
        world.setBlockState(mutable, Blocks.CAVE_AIR.getDefaultState(), 2);

        // Dynamically generate stem of structure to ensure it doesn't float
        for (int localX = 4; localX <= 7; localX++) {
            for (int localZ = 4; localZ <= 7; localZ++) {
                // Don't build on corners of stem
                if ((localX == 4 && localZ == 4) || (localX == 7 && localZ == 4) || (localX == 4 && localZ == 7) || (localX == 7 && localZ == 7)) {
                    continue;
                }

                mutable.setPos(pos.getX() + localX, pos.getY() - 1, pos.getZ() + localZ);
                BlockState currBlock = world.getBlockState(mutable);

                while (mutable.getY() > 0 && (currBlock.getMaterial() == Material.AIR || !currBlock.getFluidState().isEmpty())) {
                    world.setBlockState(mutable, selector.get(random), 2);
                    mutable.move(Direction.DOWN);
                    currBlock = world.getBlockState(mutable);
                }
            }
        }

        return true;
    }
}
